/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.evolenta.app;

import ru.evolenta.list.LinkedList;

import static ru.evolenta.utilities.StringUtils.join;
import static ru.evolenta.utilities.StringUtils.split;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(MessageUtils.getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
